[package]
name = "lpcxpresso55s69-pac"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = { version = "0.7", optional = true }
critical-section = { version = "1.2.0", optional = true }
vcell = "0.1.3"

[features]
rt = ["cortex-m-rt/device"]
